### PR TITLE
Combine pack and pdsc commands

### PR DESCRIPTION
**Pull request by chaws**
Fix https://github.com/Open-CMSIS-Pack/cpackget/issues/37 
Fix https://github.com/Open-CMSIS-Pack/cpackget/issues/35 

This patch deprecates `cpackget pack` and `cpackget pdsc` commands and combines them into one.
Now packs can be added as
```bash
$ cpackget add ARM.CMSIS
$ cpackget add ARM::CMSIS
$ cpackget add ARM::CMSIS@5.7.0
$ cpackget add ARM.CMSIS.5.7.0.pack
$ cpackget add https://keil.com/packs/ARM.CMSIS.5.7.0.pack
$ cpackget add path/to/ARM.CMSIS.pdsc # Note this is a PDSC file
```
cpackget will be smart enough to identify whether the incoming path is a packID, a pack file or URL, or even a pack's PDSC file. In the latter, cpackget will simply behave as `cpackget pdsc add path/to/ARM.CMSIS.pdsc`

This is also valid for removing packs:
```bash
$ cpackget rm ARM.CMSIS.5.7.0
```
First, cpackget will attempt looking in `CMSIS_PACK_ROOT/ARM/CMSIS/5.7.0` folder looking for such pack. If the pack is not there, cpackget looks in `.Local/local_repository.pidx` for a matching tag, then remove it any.

Lastly, `cpackget list` lists both installed packs and packs listed in `.Local/local_repository.pidx` as reported in https://github.com/Open-CMSIS-Pack/cpackget/issues/37

### CODE REVIEW

**Comment by jkrech** [comment]
I am a bit concerned about the 'pack rm' regarding the removal of the pdsc file from the local_repository.pidx :
a) please ensure that the version information is read from the pdsc file being referenced from the local_repository.pidx and not the version attribute in the pidx file
b) you may run into a situation where the same version of a pack is installed and referenced by the local_repository.pidx. I am not sure what the expected outcome should be in this case. 
c) the command should in any case support the use case that the user specifies the path to a pdsc file to remove it from the local_repository.pidx as it is supported with the cpackget add. 
I'd like other people's view on it, but I was expecting that in order to remove a pdsc file from the local_repository.pidx people would always have to specify the path + pdsc file.

**Comment by chaws** [comment]
Hi @jkrech 

> a) please ensure that the version information is read from the pdsc file being referenced from the local_repository.pidx and not the version attribute in the pidx file

I'm not sure I follow. If `cpackget rm ARM.CMSIS.5.7.0-beta` is called and this is present in "local_repository.pidx", should cpackget first validate if the pdsc referenced actually contains the version? If so, I think this is validated during installation. I need to confirm.

> b) you may run into a situation where the same version of a pack is installed and referenced by the local_repository.pidx. I am not sure what the expected outcome should be in this case.

I don't recall validating that at all during pack installation. So as it is today, it's possible to have `cpackget add ARM.CMSIS.5.7.0-beta` and `cpackget add path/to/ARM.CMSIS.pdsc` and those versions would be exactly the same. Is that something we want raise an error when it happens?

> c) the command should in any case support the use case that the user specifies the path to a pdsc file to remove it from the local_repository.pidx as it is supported with the cpackget add.
I'd like other people's view on it, but I was expecting that in order to remove a pdsc file from the local_repository.pidx people would always have to specify the path + pdsc file.

I'm fine with what people decide, I just wanted to make `cpackget rm` more convenient so the user wouldn't have to worry about the exact location of the pack just to get it removed from local_repository.pidx

**Comment by jkrech** [comment]
a) An installed pack is read only(!)  and a pdsc file being registered in the local_repository.pidx is writeable. Therefore the version specified in the pdsc may change at any point since the installation. This is the reason why the cpackget rm would need to explicitly read the pdsc file to know the actual version. BTW this is also true for listing "installed pack versions" from the local_repository.pidx!
b) Having the same version of a pack installed and registered in local_repository.pidx is not a problem for the tools, because it is defined that in this case the version of the local_repository.pidx would take precedence. This means you don't need to check for this during installation. However if the same pack version should be registered in the local_repository.pidx needs to be prevented. Since it will be unspecified which of the pack versions from the local_repository.pidx would be used by tools.
c) if 'cpackget' lists the installed and local_repository.pidx registered packs including the 'installation folder' / 'path + pdsc filename' people can just copy it from there. But I agree it is not as convenient as specifying the packID.

**Comment by chaws** [comment]
Hi @jkrech, I have updated this PR so that listing local packs installed via PDSC is layed out like:
```bash
$ ./build/cpackget list
I: Using pack root: "../packroot"
I: Listing installed packs
I: ARM.CMSIS.4.3.0
I: ARM.CMSIS.4.4.0
I: ARM.CMSIS.5.7.0
I: ARM.CMSIS.5.8.0
I: AWS.coreHTTP.2.0.0-Beta
I: TheVendor.DevPack.1.2.3 (installed via /home/chaws/linaro/src/arm/cpackget/testdata/devpack/1.2.3/TheVendor.DevPack.pdsc)
```

It lists the absolute path of the installed PDSC. This can be useful when users want to remove PDSC files using the full path as we discussed.

I'll implement the other features on new PRs so we don't overload this one.

**Comment by jkrech** [comment]
@chaws and @brondani  could we please align on the output of the tools (cpackget and csolution) when we list packs?
a) probably we should use the <vendor>::<packname>@<version> format
b) specify the location of pack versions that come from 
- $CMSIS_PACK_ROOT/.Local/local_repository.pidx
- *.csolution.yml with solution relative path (csolution only!)

**Comment by ReinhardKeil** [comment]
For listing packs, I would propose to use the same format as in the *.yml files: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#pack-name-conventions
 
This is inline with @jkrech suggestion to use :: @ in the output.

**Pull request merged**
