### PR TITLE
Add EULA checking

### PR DESCRIPTION
**Pull request by chaws**
Close https://github.com/Open-CMSIS-Pack/cpackget/issues/6

Packs specifying a `<license>` tag will be asked for user's consent of the license. cpackget will prompt a window with the license contents like the one below:

Screenshot from 2021-10-11 23-46-54

The user shall type `A` for accepting the license, `D` if that is not desired or `E` to extract the embedded license file. Both `D` and `E` options force pack installation to be interrupted. Scrolling is enabled via arrows up/down and page up/down. The "space" and "enter" keys will also scroll down the license content.

The flag `--agree-embedded-license` should be specified to cpackget in case license agreement is intended to be automatically agreed (for instance in CI systems). In this case, cpackget will print out a line saying that the user has agreed to the embedded license and will point out the full license path in the pack folder.

The flag `--extract-embedded-license` will act just like selecting `E` in the license window: it'll simply extract the license next to the pack and exit.

Also, licenses in RTF format are supported.

### CODE REVIEW

**Comment by chaws** [comment]
Record for myself: the checks failed due to missing /dev/tty, need to check if the library can support pure ASCII ui.

**Comment by jkrech** [comment]
It may seem like a tiny detail, but the commandline option: --no-license-check will not be acceptable from a legal perspective.
```--agree-embedded-license```

Ideally in the output window we extract the pack to the full path and name of the extracted license file.

We may also have a command that does not install the pack but only extracts the license file.
```--extract-license```

**Review by jkrech — CHANGES_REQUESTED** [review]
Would it be possible to support:
- rtf file format
- pdf file format

Please rename the command line option.

**Comment by chaws** [comment]
Thanks for the feedback @jkrech !

> It may seem like a tiny detail, but the commandline option: --no-license-check will not be acceptable from a legal perspective.
> `--agree-embedded-license`

Not a problem, will do that.

> 
> Ideally in the output window we extract the pack to the full path and name of the extracted license file.
> 

I'm not sure I follow this one?

> We may also have a command that does not install the pack but only extracts the license file.
> `--extract-license`

We can have that, where would the license go? Under ".Download" folder? 

> Would it be possible to support:
> 
> * rtf file format
> * pdf file format

Support as in opening the file with an external viewer tool or converting PDF/RTF into plain text?

**Review by jkrech — APPROVED** [review]

**Pull request merged**
