### PR TITLE
Fetch refs to fix aarch64 tests

### PR DESCRIPTION
**Pull request by spcaipers-arm**
Issue: #132

### CODE REVIEW

**Comment by lud0v1c** [comment]
Looks like it's not a fan of the release workflow: https://github.com/Open-CMSIS-Pack/cpackget/actions/runs/3463773563/jobs/5784470116

**Comment by spcaipers-arm** [comment]
Hi Luis, let me have a look at it... didn't test the release flow :(

**Comment by spcaipers-arm** [comment]
HI @lud0v1c, I tried to repro in my fork. No success, can you re-run the workflow and see what happens?

You can see mine here:
https://github.com/spcaipers-arm/cpackget/actions/runs/3478643210/jobs/5816245071

**Comment by lud0v1c** [comment]
Hmm I think it might be related to the tag, as I had to retag the release after doing it. Let me try on my personal fork.

**Comment by spcaipers-arm** [comment]
Hi @lud0v1c , any luck so far?

**Comment by lud0v1c** [comment]
Having some issues with triggering a release on my fork, will let you know ASAP

**Comment by lud0v1c** [comment]
Also checked the other releases (https://github.com/Open-CMSIS-Pack/cpackget/commit/baaddae23238fb57afd7c6559a339fe809e38f6c and https://github.com/Open-CMSIS-Pack/cpackget/commit/64dc2023198247efab79ae28b12b1c98e9934db2), it seems that they are also of the `(pull)` type, so I'm guessing cause of the error on this latest release was me [reapplying the tag](https://github.com/Open-CMSIS-Pack/cpackget/actions/runs/3463773563/jobs/5784470116): ` error: cannot update ref 'refs/heads/local_branch': trying to write non-commit object 21230a8f70690225783910924bee78b9da3d26c3 to branch 'refs/heads/local_branch'`

**Comment by spcaipers-arm** [comment]
Thanks @lud0v1c, so are you happy with the solution then? Are no actions required on my part?

**Comment by lud0v1c** [comment]
Yup, we will confirm its behavior on the next release, but for everything else, it works great. Thanks!

**Pull request merged**
