### PR TITLE
Make sure pack version exists in the pdsc file and it is the latest one

### PR DESCRIPTION
**Pull request by chaws**
Fix https://github.com/Open-CMSIS-Pack/cpackget/issues/43

This adds a sanity check that makes sure the pack version being installed actually exists in its PDSC file.

### CODE REVIEW

**Comment by jkrech** [comment]
Can we be more specific which copy of the pdsc file are you looking at? 
If it is the pdsc file within the pack file, then it must be latest version in the <releases> section and it is mandated that the latest version is at the top of the list.

**Comment by chaws** [comment]
@jkrech this time it uses the PDSC file from within the pack being installed.

Hum, that's a good check too! My patch only checks if the version of the pack being installed exists in the PDSC file, but I guess it could also make sure that the version is the latest one on the file as well. Let me update the patch

**Comment by jkrech** [comment]
In case the version in the contained pdsc of a pack does not match the version provided as part of the filename, can you please confirm that you refusing to install the pack? People would have to change the pack file name in order to make the installation successful?

**Comment by chaws** [comment]
> can you please confirm that you refusing to install the pack? People would have to change the pack file name in order to make the installation successful?

Yes, that's the idea. The pack information such as vendor, pack name and version are retrieved from the *.pack file name. The version is then sanity-checked against the version inside the pack's pdsc file.

**Comment by jkrech** [comment]
Sounds good to me.

**Pull request merged**
